"""Tool layer: what an agent is allowed to look at and do to the environment."""

from app.tools.investigation import (
    get_active_sessions,
    get_asset_status,
    get_cloud_activity,
    get_cloud_drive_activity,
    get_data_access_activity,
    get_dns_activity,
    get_endpoint_status,
    get_environment_summary,
    get_file_activity,
    get_github_activity,
    get_mailbox_activity,
    get_mailbox_rules,
    get_network_activity,
    get_oauth_activity,
    get_persistence_entries,
    get_process_activity,
    get_recent_logins,
    get_registered_devices,
    get_security_alerts,
    get_timeline,
    get_tokens,
)
from app.tools.registry import BLUE_TOOL_REGISTRY, blue_tool_names, call_blue_tool
from app.tools.response import (
    ACTION_IMPACT,
    IAM_FAULT,
    block_ip,
    block_simulated_connection,
    disable_user,
    isolate_endpoint,
    protect_data_asset,
    remove_mailbox_rule,
    remove_persistence_entry,
    remove_registered_device,
    restrict_asset,
    revoke_token,
    terminate_session,
    terminate_synthetic_process,
)
from app.tools.verification import verify_environment

__all__ = [
    "ACTION_IMPACT",
    "BLUE_TOOL_REGISTRY",
    "IAM_FAULT",
    "block_ip",
    "block_simulated_connection",
    "blue_tool_names",
    "call_blue_tool",
    "disable_user",
    "get_active_sessions",
    "get_asset_status",
    "get_cloud_activity",
    "get_cloud_drive_activity",
    "get_data_access_activity",
    "get_dns_activity",
    "get_endpoint_status",
    "get_environment_summary",
    "get_file_activity",
    "get_github_activity",
    "get_mailbox_activity",
    "get_mailbox_rules",
    "get_network_activity",
    "get_oauth_activity",
    "get_persistence_entries",
    "get_process_activity",
    "get_recent_logins",
    "get_registered_devices",
    "get_security_alerts",
    "get_timeline",
    "get_tokens",
    "isolate_endpoint",
    "protect_data_asset",
    "remove_mailbox_rule",
    "remove_persistence_entry",
    "remove_registered_device",
    "restrict_asset",
    "revoke_token",
    "terminate_session",
    "terminate_synthetic_process",
    "verify_environment",
]
